apiVersion: v1
kind: Service
metadata:
  name: {{ include "unleash-proxy.fullname" . }}
  labels:
    {{- include "unleash-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.nodePort)) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      protocol: TCP
      name: http
  selector:
    {{- include "unleash-proxy.selectorLabels" . | nindent 4 }}
